# Generated by Django 6.1.1 on 2026-09-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0003_blogpagetags_blogdetail_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail',
            name='body',
        ),
    ]
