# Generated by Django 6.1.1 on 2026-09-29 17:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0007_author_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('page', 0), ('image', 1), ('document', 2), ('author_profile', 3), ('call_to_action_1', 7)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage'], 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.Author',), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 4), ('page', 5), ('button_text', 6)]], {'label': 'CTA #1'})}, null=True),
        ),
    ]
