# Generated by Django 6.1.1 on 2026-10-02 13:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0008_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('page', 0), ('info', 1), ('faq', 5), ('image', 6), ('document', 7), ('author_profile', 8), ('call_to_action_1', 11)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage'], 'required': False}), 1: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Content divider with extra information'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('question', 2), ('answer', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Frequently Asked Questions', 'max_num': 5, 'min_num': 1}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 8: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.Author',), {}), 9: ('wagtail.blocks.PageChooserBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 3), ('page', 9), ('button_text', 10)]], {'label': 'CTA #1'})}, null=True),
        ),
    ]
