# Generated by Django 6.1.1 on 2026-10-03 21:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0009_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('page', 0), ('info', 1), ('faq', 2), ('text', 3), ('image', 4), ('document', 5), ('author_profile', 6), ('call_to_action_1', 10)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage'], 'required': False}), 1: ('blocks.blocks.InfoBlock', (), {}), 2: ('blocks.blocks.FAQListBlock', (), {}), 3: ('blocks.blocks.TextBlock', (), {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 6: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.Author',), {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 8: ('wagtail.blocks.PageChooserBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 7), ('page', 8), ('button_text', 9)]], {'label': 'CTA #1'})}, null=True),
        ),
    ]
