# Generated by Django 6.1.1 on 2026-10-04 16:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0010_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('page', 0), ('info', 1), ('faq', 2), ('text', 3), ('image', 4), ('document', 5), ('author_profile', 6), ('carousel', 11), ('call_to_action_1', 15)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['home.HomePage'], 'required': False}), 1: ('blocks.blocks.InfoBlock', (), {}), 2: ('blocks.blocks.FAQListBlock', (), {}), 3: ('blocks.blocks.TextBlock', (), {}), 4: ('blocks.blocks.ImageBlock', (), {}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 6: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.Author',), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('author', 9)]], {}), 11: ('wagtail.blocks.StreamBlock', [[('image', 7), ('quotation', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 13: ('wagtail.blocks.PageChooserBlock', (), {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('text', 12), ('page', 13), ('button_text', 14)]], {})}, null=True),
        ),
    ]
