# Generated by Django 6.1.1 on 2026-10-06 15:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0011_alter_blogdetail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetail',
            name='body',
            field=wagtail.fields.StreamField([('faq', 0), ('author_profile', 1), ('carousel', 6), ('call_to_action_1', 10), ('page', 11), ('info', 12), ('text', 13), ('image', 14), ('document', 15)], blank=True, block_lookup={0: ('blocks.blocks.FAQListBlock', (), {}), 1: ('wagtail.snippets.blocks.SnippetChooserBlock', ('blogpages.Author',), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('text', 3), ('author', 4)]], {}), 6: ('wagtail.blocks.StreamBlock', [[('image', 2), ('quotation', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'required': True}), 8: ('wagtail.blocks.PageChooserBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('text', 7), ('page', 8), ('button_text', 9)]], {}), 11: ('wagtail.blocks.PageChooserBlock', (), {'group': 'Standalone blocks', 'page_type': ['home.HomePage'], 'required': False}), 12: ('blocks.blocks.InfoBlock', (), {}), 13: ('blocks.blocks.TextBlock', (), {}), 14: ('blocks.blocks.ImageBlock', (), {}), 15: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'group': 'Standalone blocks'})}, null=True),
        ),
    ]
